// Priority V1 asset manifest: hero + core monsters/boss + rarity icons first,
// per DESIGN_NOTES.md — the rest of the roster can be appended and re-run later
// without touching generated files (the script skips anything already on disk).
export const manifest = [
  { id: 'knight', category: 'hero', prompt: 'a heroic young knight in ornate silver plate armor, sword and shield raised, noble determined expression' },
  {
    id: 'berserker',
    category: 'hero',
    prompt: 'a fierce battle-scarred barbarian berserker wielding a massive twin-bladed axe, wild hair, rage-filled eyes, tribal armor',
  },
  {
    id: 'guardian',
    category: 'hero',
    prompt: 'a stalwart armored guardian knight with a massive tower shield and heavy blue-accented plate armor, unshakeable defensive stance',
  },
  {
    id: 'duelist',
    category: 'hero',
    prompt: 'a swift agile duelist swordsman in a sleek gold-trimmed coat, rapier in hand, confident dashing pose',
  },
  { id: 'goblin_grunt', category: 'monsters', prompt: 'a small snarling green goblin warrior with a crude dagger' },
  { id: 'slime', category: 'monsters', prompt: 'a translucent blue gelatinous slime monster with a simple cute face' },
  { id: 'wolf', category: 'monsters', prompt: 'a fierce grey dire wolf baring its fangs, low crouching stance' },
  { id: 'skeleton', category: 'monsters', prompt: 'an undead skeleton warrior in tattered armor holding a rusty sword' },
  { id: 'bat', category: 'monsters', prompt: 'a small screeching cave bat with leathery wings' },
  { id: 'orc_chieftain', category: 'monsters', prompt: 'a hulking orc chieftain with tribal armor and a massive battle axe, miniboss' },
  { id: 'ancient_wyrm', category: 'monsters', prompt: 'an ancient purple dragon wyrm with glowing eyes, epic boss monster, imposing' },
  { id: 'giant_rat', category: 'monsters', prompt: 'a scruffy oversized rat with sharp teeth, feral' },
  { id: 'forest_spider', category: 'monsters', prompt: 'a large venomous forest spider with glowing eyes' },
  { id: 'bandit_thug', category: 'monsters', prompt: 'a rough human bandit thug with a hood and a club' },
  { id: 'swamp_troll', category: 'monsters', prompt: 'a hulking green swamp troll covered in muck, brutish' },
  { id: 'shade_wraith', category: 'monsters', prompt: 'a ghostly dark shade wraith made of smoke and shadow, glowing eyes' },
  { id: 'troll_berserker', category: 'monsters', prompt: 'a massive raging troll berserker with battle scars, miniboss' },
  { id: 'venomous_broodmother', category: 'monsters', prompt: 'a monstrous venomous spider broodmother, miniboss, many eyes' },
  { id: 'frost_lich', category: 'monsters', prompt: 'an undead frost lich in icy tattered robes, glowing blue eyes, boss monster' },
  { id: 'inferno_golem', category: 'monsters', prompt: 'a massive molten stone golem wreathed in fire, boss monster, imposing' },
  {
    id: 'colossus_of_ash',
    category: 'monsters',
    prompt: 'a colossal ash-grey stone titan wreathed in smoldering cinders, cracked glowing molten veins, megaboss, towering and imposing',
  },
  {
    id: 'gravemind_hydra',
    category: 'monsters',
    prompt: 'a monstrous three-headed hydra made of bone and shadow, glowing violet eyes, megaboss, terrifying',
  },
  {
    id: 'the_unmaking',
    category: 'monsters',
    prompt:
      'an apocalyptic void entity of shattered cosmic armor and swirling dark energy, ultraboss, final boss, overwhelming presence, radiant black and gold',
  },
  { id: 'rarity_common', category: 'icons', prompt: 'a simple grey gemstone icon, plain and dull' },
  { id: 'rarity_rare', category: 'icons', prompt: 'a glowing blue sapphire gemstone icon' },
  { id: 'rarity_epic', category: 'icons', prompt: 'a glowing purple amethyst gemstone icon' },
  { id: 'rarity_legendary', category: 'icons', prompt: 'a glowing golden orange topaz gemstone icon, radiant' },
  { id: 'rarity_mythic', category: 'icons', prompt: 'a glowing rainbow prismatic crystal icon, ethereal, magical' },

  // Gacha companions: each gets two assets — a menu illustration (style: 'illustration') and a
  // combat pixel-art sprite (style: 'pixelArt', category 'companions' so CombatScene's existing
  // texture loading picks it up with zero code changes). See generate.mjs for the style suffixes.
  {
    id: 'stalwart_guardian',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'a stalwart armored guardian knight holding a tower shield, protective stance',
  },
  {
    id: 'stalwart_guardian',
    category: 'companions',
    style: 'pixelArt',
    prompt: 'a stalwart armored guardian knight holding a tower shield, protective stance',
  },
  {
    id: 'roguish_blade',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'a quick roguish swordsman in a hood with twin daggers, agile pose',
  },
  {
    id: 'roguish_blade',
    category: 'companions',
    style: 'pixelArt',
    prompt: 'a quick roguish swordsman in a hood with twin daggers, agile pose',
  },
  {
    id: 'arcane_marksman',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'an elegant spellsword archer channeling arcane energy into a glowing bow',
  },
  {
    id: 'arcane_marksman',
    category: 'companions',
    style: 'pixelArt',
    prompt: 'an elegant spellsword archer channeling arcane energy into a glowing bow',
  },
  {
    id: 'wandering_cleric',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'a serene traveling cleric in white and gold robes holding a healing staff',
  },
  {
    id: 'wandering_cleric',
    category: 'companions',
    style: 'pixelArt',
    prompt: 'a serene traveling cleric in white and gold robes holding a healing staff',
  },
  {
    id: 'camp_bard',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'a charming bard with a lute, mid-performance, energetic pose',
  },
  { id: 'camp_bard', category: 'companions', style: 'pixelArt', prompt: 'a charming bard with a lute, mid-performance, energetic pose' },
  {
    id: 'ember_wisp',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'a small floating spirit wisp made of flickering fire, mischievous glowing eyes',
  },
  {
    id: 'ember_wisp',
    category: 'companions',
    style: 'pixelArt',
    prompt: 'a small floating spirit wisp made of flickering fire, mischievous glowing eyes',
  },
  {
    id: 'crimson_dragoon',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'a legendary dragoon in crimson dragon-scale armor wielding a long lance, dramatic heroic pose',
  },
  {
    id: 'crimson_dragoon',
    category: 'companions',
    style: 'pixelArt',
    prompt: 'a legendary dragoon in crimson dragon-scale armor wielding a long lance, dramatic heroic pose',
  },
  {
    id: 'astral_seraph',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'a mythic celestial seraph with glowing golden wings and radiant halo, ethereal divine aura',
  },
  {
    id: 'astral_seraph',
    category: 'companions',
    style: 'pixelArt',
    prompt: 'a mythic celestial seraph with glowing golden wings and radiant halo, ethereal divine aura',
  },
  {
    id: 'iron_vanguard',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'a veteran armored vanguard knight with a massive tower shield and battle-worn plate, unshakeable defensive stance',
  },
  {
    id: 'iron_vanguard',
    category: 'companions',
    style: 'pixelArt',
    prompt: 'a veteran armored vanguard knight with a massive tower shield and battle-worn plate, unshakeable defensive stance',
  },
  {
    id: 'hearthkeeper',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'a hardened field medic in warm earthen robes holding a glowing mending staff, calm and resolute',
  },
  {
    id: 'hearthkeeper',
    category: 'companions',
    style: 'pixelArt',
    prompt: 'a hardened field medic in warm earthen robes holding a glowing mending staff, calm and resolute',
  },
  {
    id: 'warlords_aegis',
    category: 'companions_illustration',
    style: 'illustration',
    prompt: 'a battle-worn banner-bearer holding a great standard and a rune-etched aegis shield, commanding heroic stance',
  },
  {
    id: 'warlords_aegis',
    category: 'companions',
    style: 'pixelArt',
    prompt: 'a battle-worn banner-bearer holding a great standard and a rune-etched aegis shield, commanding heroic stance',
  },
];
